services:
  - type: web
    name: detecta-boletos
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: detecta-boletos-db
          property: connectionString
      - key: MODEL_PATH
        value: modelo/modelo_boleto.pkl

databases:
  - name: detecta-boletos-db
    databaseName: detecta_boletos
    user: detecta_user
